# Site settings
title: "Dzmitry Bahdanau Webpage&Blog"
description: > # this means to ignore newlines until "baseurl:"
    Opinions, idea, errata
baseurl: ""
url: "https://rizar.github.io/"
github_username:  rizar

# Build settings
markdown: kramdown
